version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gp-resource-admin
      POSTGRES_PASSWORD: vanishingbudget
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
