export const nros = [
  { 
    name: 'Africa',
    incomeGrants: 5170,
    incomeFundraising: 0,
    incomeOther: 5,
    expensesContributions: 0,
    expensesCampaigns: 1698,
    expensesCampaignSupport: 1176,
    expensesOrgSupport: 2334,
    staffCampaigns: 29,
    staffFundraising: 14,
    staffOrgSupport: 27,
    staffCampaignSupport: 26,
  },
  {
    name: 'Andino',
    incomeGrants: 0,
    incomeFundraising: 7823,
    incomeOther: 168,
    expensesContributions: 1966,
    expensesCampaigns: 2316,
    expensesCampaignSupport: 2502,
    expensesOrgSupport: 1781,
    staffCampaigns: 16,
    staffFundraising: 27.5,
    staffOrgSupport: 18,
    staffCampaignSupport: 36,
  },
  {
    name: 'Aus Pac',
    incomeGrants: 285,
    incomeFundraising: 6734,
    incomeOther: 63,
    expensesContributions: 2518,
    expensesCampaigns: 1254,
    expensesCampaignSupport: 2343,
    expensesOrgSupport: 1633,
    staffCampaigns: 8.1,
    staffFundraising: 15.1,
    staffOrgSupport: 13.2,
    staffCampaignSupport: 25,
  },
  {
    name: 'Belgium',
    incomeGrants: 0,
    incomeFundraising: 7644,
    incomeOther: 180,
    expensesContributions: 3213,
    expensesCampaigns: 1696,
    expensesCampaignSupport: 2900,
    expensesOrgSupport: 1102,
    staffCampaigns: 14.4,
    staffFundraising: 25.9,
    staffOrgSupport: 12.3,
    staffCampaignSupport: 30,
  },
  {
    name: 'Brazil',
    incomeGrants: 6260,
    incomeFundraising: 2715,
    incomeOther: 114,
    expensesContributions: 0,
    expensesCampaigns: 3453,
    expensesCampaignSupport: 3455,
    expensesOrgSupport: 2182,
    staffCampaigns: 33,
    staffFundraising: 151,
    staffOrgSupport: 29,
    staffCampaignSupport: 40,
  },
  {
    name: 'Canada',
    incomeGrants: 482,
    incomeFundraising: 3580,
    incomeOther: 3,
    expensesContributions: 1395,
    expensesCampaigns: 923,
    expensesCampaignSupport: 848,
    expensesOrgSupport: 1066,
    staffCampaigns: 14.5,
    staffFundraising: 12.1,
    staffOrgSupport: 12.2,
    staffCampaignSupport: 15,
  },
  {
    name: 'CEE',
    incomeGrants: 1467,
    incomeFundraising: 8052,
    incomeOther: 4,
    expensesContributions: 3043,
    expensesCampaigns: 3210,
    expensesCampaignSupport: 1830,
    expensesOrgSupport: 2127,
    staffCampaigns: 43.4,
    staffFundraising: 91.5,
    staffOrgSupport: 30,
    staffCampaignSupport: 37,
  },
  {
    name: 'Czech',
    incomeGrants: 93,
    incomeFundraising: 403,
    incomeOther: 0,
    expensesContributions: 62,
    expensesCampaigns: 159,
    expensesCampaignSupport: 257,
    expensesOrgSupport: 153,
    staffCampaigns: 5,
    staffFundraising: 4.6,
    staffOrgSupport: 3.8,
    staffCampaignSupport: 5,
  },
  {
    name: 'East Asia',
    incomeGrants: 14441,
    incomeFundraising: 13559,
    incomeOther: 10,
    expensesContributions: 88295,
    expensesCampaigns: 7001,
    expensesCampaignSupport: 7689,
    expensesOrgSupport: 5345,
    staffCampaigns: 75.4,
    staffFundraising: 236.5,
    staffOrgSupport: 55.6,
    staffCampaignSupport: 112,
  },
  {
    name: 'EU',
    incomeGrants: 2100,
    incomeFundraising: 0,
    incomeOther: 0,
    expensesContributions: 0,
    expensesCampaigns: 0,
    expensesCampaignSupport: 2058,
    expensesOrgSupport: 42,
    staffCampaigns: 0,
    staffFundraising: 0,
    staffOrgSupport: 0,
    staffCampaignSupport: 19,
  },
  {
    name: 'Fr-Lux',
    incomeGrants: 0,
    incomeFundraising: 15884,
    incomeOther: 26,
    expensesContributions: 6124,
    expensesCampaigns: 3390,
    expensesCampaignSupport: 4130,
    expensesOrgSupport: 2160,
    staffCampaigns: 23.1,
    staffFundraising: 69,
    staffOrgSupport: 16,
    staffCampaignSupport: 37,
  },
  {
    name: 'Germany',
    incomeGrants: 0,
    incomeFundraising: 46361,
    incomeOther: 413,
    expensesContributions: 24253,
    expensesCampaigns: 9640,
    expensesCampaignSupport: 14449,
    expensesOrgSupport: 4851,
    staffCampaigns: 48.6,
    staffFundraising: 68.3,
    staffOrgSupport: 39.6,
    staffCampaignSupport: 85,
  },
  {
    name: 'Greece',
    incomeGrants: 0,
    incomeFundraising: 844,
    incomeOther: 1,
    expensesContributions: 109,
    expensesCampaigns: 322,
    expensesCampaignSupport: 178,
    expensesOrgSupport: 204,
    staffCampaigns: 9,
    staffFundraising: 19.0,
    staffOrgSupport: 5.5,
    staffCampaignSupport: 8,
  },
  {
    name: 'Italy',
    incomeGrants: 140,
    incomeFundraising: 4911,
    incomeOther: 0,
    expensesContributions: 2329,
    expensesCampaigns: 1084,
    expensesCampaignSupport: 1279,
    expensesOrgSupport: 1116,
    staffCampaigns: 11.1,
    staffFundraising: 20.1,
    staffOrgSupport: 9.6,
    staffCampaignSupport: 12,
  },
  {
    name: 'Japan',
    incomeGrants: 1142,
    incomeFundraising: 691,
    incomeOther: 1,
    expensesContributions: 16,
    expensesCampaigns: 763,
    expensesCampaignSupport: 805,
    expensesOrgSupport: 525,
    staffCampaigns: 9.1,
    staffFundraising: 12,
    staffOrgSupport: 7,
    staffCampaignSupport: 12,
  },
  {
    name: 'MENA',
    incomeGrants: 779,
    incomeFundraising: 6,
    incomeOther: 0,
    expensesContributions: 0,
    expensesCampaigns: 153,
    expensesCampaignSupport: 254,
    expensesOrgSupport: 363,
    staffCampaigns: 2,
    staffFundraising: 0,
    staffOrgSupport: 4,
    staffCampaignSupport: 4,
  },
  {
    name: 'Mexico',
    incomeGrants: 0,
    incomeFundraising: 2434,
    incomeOther: 56,
    expensesContributions: 209,
    expensesCampaigns: 710,
    expensesCampaignSupport: 587,
    expensesOrgSupport: 715,
    staffCampaigns: 8,
    staffFundraising: 24,
    staffOrgSupport: 11,
    staffCampaignSupport: 13,
  },
  {
    name: 'Nordic',
    incomeGrants: 0,
    incomeFundraising: 14760,
    incomeOther: 0,
    expensesContributions: 6437,
    expensesCampaigns: 3265,
    expensesCampaignSupport: 3060,
    expensesOrgSupport: 1946,
    staffCampaigns: 26.2,
    staffFundraising: 31.3,
    staffOrgSupport: 17.5,
    staffCampaignSupport: 35,
  },
  {
    name: 'New Zealand',
    incomeGrants: 116,
    incomeFundraising: 2844,
    incomeOther: 13,
    expensesContributions: 1207,
    expensesCampaigns: 594,
    expensesCampaignSupport: 738,
    expensesOrgSupport: 688,
    staffCampaigns: 7.9,
    staffFundraising: 36.6,
    staffOrgSupport: 8.7,
    staffCampaignSupport: 10,
  },
  {
    name: 'Russia',
    incomeGrants: 3820,
    incomeFundraising: 2,
    incomeOther: 0,
    expensesContributions: 6,
    expensesCampaigns: 2350,
    expensesCampaignSupport: 1050,
    expensesOrgSupport: 644,
    staffCampaigns: 45.2,
    staffFundraising: 9.5,
    staffOrgSupport: 15.9,
    staffCampaignSupport: 31,
  },
  {
    name: 'SEA',
    incomeGrants: 6205,
    incomeFundraising: 1042,
    incomeOther: 0,
    expensesContributions: 0,
    expensesCampaigns: 3806,
    expensesCampaignSupport: 1656,
    expensesOrgSupport: 1878,
    staffCampaigns: 48,
    staffFundraising: 37,
    staffOrgSupport: 50.5,
    staffCampaignSupport: 49,
  },
  {
    name: 'Spain',
    incomeGrants: 0,
    incomeFundraising: 9036,
    incomeOther: 0,
    expensesContributions: 3681,
    expensesCampaigns: 2907,
    expensesCampaignSupport: 1857,
    expensesOrgSupport: 1520,
    staffCampaigns: 16,
    staffFundraising: 14.3,
    staffOrgSupport: 13,
    staffCampaignSupport: 17,
  },
  {
    name: 'Switzerland',
    incomeGrants: 0,
    incomeFundraising: 13934,
    incomeOther: 24,
    expensesContributions: 8002,
    expensesCampaigns: 1648,
    expensesCampaignSupport: 3299,
    expensesOrgSupport: 1510,
    staffCampaigns: 8,
    staffFundraising: 29,
    staffOrgSupport: 12,
    staffCampaignSupport: 22,
  },
  {
    name: 'UK',
    incomeGrants: 0,
    incomeFundraising: 17400,
    incomeOther: 0,
    expensesContributions: 7943,
    expensesCampaigns: 4205,
    expensesCampaignSupport: 3707,
    expensesOrgSupport: 3278,
    staffCampaigns: 24.1,
    staffFundraising: 42.4,
    staffOrgSupport: 21,
    staffCampaignSupport: 53,
  },
  {
    name: 'USA',
    incomeGrants: 971,
    incomeFundraising: 19563,
    incomeOther: 263,
    expensesContributions: 12086,
    expensesCampaigns: 4923,
    expensesCampaignSupport: 6213,
    expensesOrgSupport: 5937,
    staffCampaigns: 33,
    staffFundraising: 224.8,
    staffOrgSupport: 60.9,
    staffCampaignSupport: 67,
  },
]
