export const nros = [
  { name: 'Africa', incomeGrants: 5170, incomeFundraising: 0, incomeOther: 5 },
  { name: 'Andino', incomeGrants: 0, incomeFundraising: 7823, incomeOther: 168 },
  { name: 'Aus Pac', incomeGrants: 285, incomeFundraising: 6734, incomeOther: 63 },
  { name: 'Belgium', incomeGrants: 0, incomeFundraising: 7644, incomeOther: 180 },
  { name: 'Brazil', incomeGrants: 6260, incomeFundraising: 2715, incomeOther: 114 },
  { name: 'Canada', incomeGrants: 482, incomeFundraising: 3580, incomeOther: 3 },
  { name: 'CEE', incomeGrants: 1467, incomeFundraising: 8052, incomeOther: 4 },
  { name: 'Czech', incomeGrants: 93, incomeFundraising: 403, incomeOther: 0 },
  { name: 'East Asia', incomeGrants: 14441, incomeFundraising: 13559, incomeOther: 10 },
  { name: 'EU', incomeGrants: 2100, incomeFundraising: 0, incomeOther: 0 },
  { name: 'Fr-Lux', incomeGrants: 0, incomeFundraising: 15884, incomeOther: 26 },
  { name: 'Germany', incomeGrants: 0, incomeFundraising: 46361, incomeOther: 413 },
  { name: 'Greece', incomeGrants: 0, incomeFundraising: 844, incomeOther: 1 },
  { name: 'Italy', incomeGrants: 140, incomeFundraising: 4911, incomeOther: 0 },
  { name: 'Japan', incomeGrants: 1142, incomeFundraising: 691, incomeOther: 1 },
  { name: 'MENA', incomeGrants: 779, incomeFundraising: 6, incomeOther: 0 },
  { name: 'Mexico', incomeGrants: 0, incomeFundraising: 2434, incomeOther: 56 },
  { name: 'Nordic', incomeGrants: 0, incomeFundraising: 14760, incomeOther: 0 },
  { name: 'New Zealand', incomeGrants: 116, incomeFundraising: 2844, incomeOther: 13 },
  { name: 'Russia', incomeGrants: 3820, incomeFundraising: 2, incomeOther: 0 },
  { name: 'SEA', incomeGrants: 6205, incomeFundraising: 1042, incomeOther: 0 },
  { name: 'Spain', incomeGrants: 0, incomeFundraising: 9036, incomeOther: 0 },
  { name: 'Switzerland', incomeGrants: 0, incomeFundraising: 13934, incomeOther: 24 },
  { name: 'UK', incomeGrants: 0, incomeFundraising: 17400, incomeOther: 0 },
  { name: 'USA', incomeGrants: 971, incomeFundraising: 19563, incomeOther: 263 },
]
